services:
  whitelisted_relay:
    build:
      context: ./sifter
      dockerfile: ./Dockerfile
    container_name: strfry_whitelisted_relay
    command: --config=config/relay.conf relay 
    volumes:
      - ./config:/app/config
      - ./resource:${RESOURCE_DIR}
      - ./strfry-db/whitelisted:/app/strfry-db
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
    env_file:
      - ./.env
    pid: host
    depends_on:
      whitelisted_follow_check_api:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "20"

  whitelisted_router:
    build:
      context: ./sifter
      dockerfile: ./Dockerfile
    container_name: strfry_whitelisted_router
    command: --config=config/relay.conf router config/router.conf
    volumes:
      - ./config:/app/config
      - ./resource:${RESOURCE_DIR}
      - ./strfry-db/whitelisted:/app/strfry-db
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
    env_file:
      - ./.env
    pid: host
    depends_on:
      whitelisted_follow_check_api:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"

  whitelisted_follow_check_api:
    build:
      context: ./follow_check_api
      dockerfile: ./Dockerfile
    container_name: whitelisted_follow_check_api
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./resource:${RESOURCE_DIR}
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./.env
    healthcheck:
      test: "wget --quiet --spider http://localhost:8080/health || exit 1"
      start_period: 10s
      interval: 30s
      timeout: 3s
      retries: 2
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    
